var artData = {
colage: {
		name: '  ',
		fullName: 'N/A',
		born: 'N/A',
		nationality: 'N/A',
		knownFor: 'N/A',
		movement: 'N/A',
		notableWork: 'N/A',
		died: 'N/A',
	},
	picasso: {
		name: 'Pablo Picasso ',
		fullName: 'Pablo Diego José Francisco Picasso',
		born: '25 October 1881',
		nationality: 'Spanish',
		knownFor: 'Painting',
		movement: ' Cubism',
		notableWork: 'Guernica (1937)',
		died: 'April 8, 1973, Mougins, France',
	},

vinci: {
		name: 'Lionardo da Vinci ',
		fullName: 'Lionardo di ser Piero da Vinci',
		born: '14/15 April 1452',
		nationality: 'Republic of Florence ,Italy',
		knownFor: 'Painting, Drawing, sculpting, ',
		movement: ' High Renaissance',
		notableWork: 'Mona Lisa,The Last Supper,',
		died: '2 May 1519 (aged 67) France',
	},
	michelangelo: {
		name: 'Michelangelo ',
		fullName: 'Michelangelo di L B Simoni',
		born: '6 March 1475',
		nationality: 'Italy)',
		knownFor: 'Sculpture, painting, architecture,',
		movement: ' High Renaissance',
		notableWork: 'David, Moses,,Sistine Chapel',
		died: '18 February 1564 (aged 88) Italy)',
	},

	robert: {
		name: ' Robert Rauschenberg',
		fullName: 'Milton Ernest Rauschenberg',
		born: 'October 22, 1925',
		nationality: ' U.S.A',
		knownFor: 'Assemblage',
		movement: 'Neo-Dada, Abstract Expressionism',
		notableWork: 'Canyon (1959),Monogram (1959)',
		died: 'May 12, 2008 (aged 82)' ,
	},
	johns: {
		name: ' Jasper Johns',
		fullName: 'Jasper Johns Jr',
		born: 'May 15, 1930 (age 89)',
		nationality: ' U.S.A',
		knownFor: 'Painting, printmaking',
		movement: 'Abstract expressionism,pop art',
		notableWork: 'Flags, Numbers, Maps, ',
		died: 'Living legent' ,
	},
	kusama: {
		name: ' Yayoi Kusama ',
		fullName: 'Yayoi Kusama Kusama Yayoi,',
		born: '22 March 1929 (age 90)',
		nationality: ' Japanese',
		knownFor: 'installation art,performance art',
		movement: 'minimalism,,environmental art',
		notableWork: 'Red Pumpkin (2006), Naoshima',
		died: 'Living legent' ,
	},
helen: {
		name: ' Helen Frankenthaler ',
		fullName: 'Helen Frankenthaler',
		born: 'December 12, 1928',
		nationality: ' U.S.A',
		knownFor: 'Painting',
		movement: ' Abstract Expressionism,',
		notableWork: 'Mountains and Sea',
		died: 'December 27, 2011 (aged 83)',
	},
	dali: {
		name: ' Salvador Dalí ',
		fullName: 'Salvador Domingo F.J i Domènech',
		born: '11 May 1904',
		nationality: ' Spanish',
		knownFor: 'Painting, writing, film, jewelry',
		movement: ' Cubism, Dada, Surrealism',
		notableWork: 'The Persistence of Memory,Crucifixion ',
		died: '23 January 1989 (aged 84)',
	},
	frida: {
				name: ' Frida Kahlo',
				fullName: 'M. C. Frida Kahlo y Calderón',
				born: '6 July 1907',
				nationality: ' Mexico',
				knownFor: 'Painting',
				movement: ' Surrealism, Magic realism',
				notableWork: 'The Two Fridas (1939),Self-Portrait',
				died: '13 July 1954 (aged 47)',
	},
	andy: {
		name: 'Andy Warhol ',
		fullName: 'Andrew Warhola',
		born: 'August 6, 1928',
		nationality: 'U.S.A',
		knownFor: 'Printmaking, painting,cinema,',
		movement: ' Pop art',
		notableWork: 'Campbell Soup Cans,MarilynDiptych ',
		died: 'February 22, 1987 (aged 58)',
	},
	matisse: {
		name: 'Henri Matisse ',
		fullName: 'Henri Émile Benoît Matisse',
		born: '31 December 1869',
		nationality: 'France',
		knownFor: 'Painting',
		movement: ' Fauvism,Post-Impressionism',
		notableWork: 'La Danse L,Atelier Rouge',
		died: '3 November 1954 (aged 84)',
	},
	vincent: {
		name: 'Vincent van Gogh',
		fullName: 'Vincent Willem van Gogh',
		born: '30 March 1853',
		nationality: 'Dutch',
		knownFor: 'Painting',
		movement: 'Post-Impressionism',
		notableWork: 'Sunflowers,The Starry Night ',
		died: '29 July 1890 (aged 37)',
	},
	gauguin: {
		name: 'Paul Gauguin ',
		fullName: 'Eugène Henri Paul Gauguin',
		born: '7 June 1848',
		nationality: 'France',
		knownFor: 'Painting, sculpture, engraving',
		movement: ' Post-Impressionism, Primitivism',
		notableWork: 'Spirit of the Dead Watching,',
		died: '8 May 1903 (aged 54)',
	},
	pollok: {
		name: 'Jackson Pollock ',
		fullName: 'Paul Jackson Pollock',
		born: 'January 28, 1912',
		nationality: 'U.S.A',
		knownFor: 'Painting',
		movement: 'Abstract expressionism',
		notableWork: 'Autumn Rhythm,Convergence',
		died: 'August 11, 1956 (aged 44)',
	},
monet: {
		name: 'Claude Monet ',
		fullName: 'Oscar-Claude Monet',
		born: '14 November 1840',
		nationality: 'France',
		knownFor: 'Painting',
		movement: ' Impressionism, Post-Impressionism',
		notableWork: 'Impression, Sunrise,Water Lilies',
		died: '5 December 1926 (aged 86)',
	},
	cezanne: {
		name: 'Paul Cézanne ',
		fullName: 'Paul Cézanne',
		born: '19 January 1839',
		nationality: 'France',
		knownFor: 'Painting,',
		movement: ' Impressionism, Post-Impressionism',
		notableWork: 'The Card Players,The Bathers ',
		died: '22 October 1906 (aged 67)',
	},
	rembrant: {
		name: 'Rembrant ',
		fullName: 'Rembrant Harmenszoon van Rijn',
		born: '15 July 1606',
		nationality: ', Dutch ',
		knownFor: 'Painting',
		movement: ' Dutch Golden Age Baroque',
		notableWork: 'The Night Watch (1642)',
		died: 'October 4, 1669 (aged 63)',
	},
	sc: {
		name: 'South Carolina',
		abbr: 'SC',
		capitol: 'Columbia',
		pop: '4,774,839',
		statehood: '1788',
		mammal: 'White-Tailed Deer',
		bird: 'Carolina Wren',
		tree: 'Sabal Palmetto',
		flower: 'Yellow Jessamine',
		nickname: 'Palmetto State'
	},
	sd: {
		name: 'South Dakota',
		abbr: 'SD',
		capitol: 'Pierre',
		pop: '844,877',
		statehood: '1889',
		mammal: 'Coyote',
		bird: 'Chinese Ring-Necked Pheasant',
		tree: 'Black Hills Spruce',
		flower: 'Pasque',
		nickname: 'Mount Rushmore State'
	},
	tn: {
		name: 'Tennessee',
		abbr: 'TN',
		capitol: 'Nashville',
		pop: '6,495,978',
		statehood: '1796',
		mammal: 'Raccoon',
		bird: 'Mockingbird',
		tree: 'Tulip Poplar',
		flower: 'Iris',
		nickname: 'Volunteer State'
	},
	tx: {
		name: 'Texas',
		abbr: 'TX',
		capitol: 'Austin',
		pop: '26,448,193',
		statehood: '1845',
		mammal: 'Longhorn',
		bird: 'Mockingbird',
		tree: 'Pecan',
		flower: 'Bluebonnet',
		nickname: 'Lone Star State'
	},
	ut: {
		name: 'Utah',
		abbr: 'UT',
		capitol: 'Salt Lake City',
		pop: '2,900,872',
		statehood: '1896',
		mammal: 'Rock-Mountain Elk',
		bird: 'California Gull',
		tree: 'Blue Spruce',
		flower: 'Sego Lily',
		nickname: 'The Beehive State'
	},
	vt: {
		name: 'Vermont',
		abbr: 'VT',
		capitol: 'Montpelier',
		pop: '626,630',
		statehood: '1791',
		mammal: 'Morgan Horse',
		bird: 'Hermit Thrush',
		tree: 'Sugar Maple',
		flower: 'Red Clover',
		nickname: 'Green Mountain State'
	},
	va: {
		name: 'Virginia',
		abbr: 'VA',
		capitol: 'Richmond',
		pop: '8,260,405',
		statehood: '1788',
		mammal: 'Virginia Big-Eared Bat',
		bird: 'Cardinal',
		tree: 'Flowering Dogwood',
		flower: 'Flowering Dogwood',
		nickname: 'Old Dominion State'
	},
kandinsky: {
		name: 'Wassily Kandinsky ',
		fullName: 'Wassily Wassilyevich Kandinsky',
		born: '16 December 1866',
		nationality: 'Russian, later French',
		knownFor: 'Painting',
		movement: 'Expressionism; abstract art',
		notableWork: 'On White II, Der Blaue Reiter',
		died: '13 December 1944 (aged 77)',
	},
	dc: {
		name: 'Washington, District of Columbia',
		abbr: 'DC',
		capitol: 'N/A',
		pop: '658,893',
		statehood: 'N/A',
		mammal: 'N/A',
		bird: 'Wood Thrush',
		tree: 'Scarlet Oak',
		flower: 'American Beauty Rose',
		nickname: 'Federal City'
	},
	wv: {
		name: 'West Virginia',
		abbr: 'WV',
		capitol: 'Charleston',
		pop: '1,854,304',
		statehood: '1863',
		mammal: 'Black Bear',
		bird: 'Cardinal',
		tree: 'Sugar Maple',
		flower: 'Rhododendron',
		nickname: 'Mountain State'
	},
	wi: {
		name: 'Wisconsin',
		abbr: 'WI',
		capitol: 'Madison',
		pop: '5,742,713',
		statehood: '1848',
		mammal: 'Badger',
		bird: 'Robin',
		tree: 'Sugar Maple',
		flower: 'Wood Violet',
		nickname: 'Badger State'
	},
	wy: {
		name: 'Wyoming',
		abbr: 'WY',
		capitol: 'Cheyenne',
		pop: '582,658',
		statehood: '1890',
		mammal: 'American Buffalo',
		bird: 'Western Meadlowlark',
		tree: 'Plains Cottonwood',
		flower: 'Indian Paintbrush',
		nickname: 'Equality State'
	}
};
